backend:
  name: github
  repo: banjo-biden/accrue-haiku
  branch: main
  auth_scope: repo
  client_id: Ov23liZBGD2FFAiB09Zz

media_folder: "src/images/uploads"
public_folder: "/src/images/uploads"

collections:
  - name: "haiku"
    label: "Haiku"
    folder: "_haiku"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Author"
        name: "author"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"